DROP TABLE free_board_file;
create table free_board_file(
    FREE_BOARD_FILE_ID NUMBER,
    FREE_BOARD_ID NUMBER NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL,
    STORED_FILE_NAME VARCHAR2(37) NOT NULL,
    FREE_BOARD_FILE_SIZE NUMBER NOT NULL,
    CREATE_DATE DATE NOT NULL,
    UPDATE_DATE DATE NOT NULL,
    CONSTRAINT FREE_BOARD_FILE_ID_PK PRIMARY KEY (FREE_BOARD_FILE_ID),
    CONSTRAINT FREE_BOARD_FILE_BOARD_ID_FK FOREIGN KEY (FREE_BOARD_ID)
        REFERENCES FREE_BOARD(FREE_BOARD_ID)
    
);

DROP SEQUENCE FREE_BOARD_FILE_ID_SEQ;
CREATE SEQUENCE FREE_BOARD_FILE_ID_SEQ
START WITH 1
INCREMENT BY 1;

DESC free_board_file;

INSERT INTO FREE_BOARD_FILE
(FREE_BOARD_FILE_ID, FREE_BOARD_ID
, ORIGINAL_FILE_NAME, STORED_FILE_NAME, FREE_BOARD_FILE_SIZE
, CREATE_DATE, UPDATE_DATE)
VALUES(FREE_BOARD_FILE_ID_SEQ.nextval, 1
, '원래 파일명.txt', '중복방지 처리된 파일명.txt', 1024
, sysdate, sysdate);

--부모 게시판 자식 파일
SELECT  M.MEMBER_NO, M.EMAIL, m.member_name, FB.FREE_BOARD_ID, 
    FB.FREE_BOARD_TITLE, FB.FREE_BOARD_CONTENT, FB.CREATE_DATE
FROM MEMBER M, FREE_BOARD FB
WHERE M.MEMBER_NO = FB.MEMBER_NO
ORDER BY FB.FREE_BOARD_ID DESC;

SELECT FBF.FREE_BOARD_FILE_ID, FB.FREE_BOARD_ID
    , FBF.ORIGINAL_FILE_NAME, FBF.STORED_FILE_NAME, FBF.FREE_BOARD_FILE_SIZE
    , fb.free_board_title
FROM FREE_BOARD FB JOIN FREE_BOARD_FILE FBF
ON fb.free_board_id = fbf.free_board_id;

rollback;

SELECT FREE_BOARD_FILE_ID_SEQ.NEXTVAL
FROM DUAL;


SELECT FB.FREE_BOARD_ID, FB.FREE_BOARD_TITLE, FB.FREE_BOARD_CONTENT
    , M.MEMBER_NAME
    , M.EMAIL
    , FB.CREATE_DATE
    , FBF.ORIGINAL_FILE_NAME, FBF.STORED_FILE_NAME
FROM FREE_BOARD FB, FREE_BOARD_FILE FBF, MEMBER M
WHERE FB.FREE_BOARD_ID = FBF.FREE_BOARD_ID 
AND FB.MEMBER_NO = M.MEMBER_NO
AND FB.FREE_BOARD_ID = 132;

SELECT FBF.FREE_BOARD_FILE_ID as "freeBoardFileId"
	, FBF.FREE_BOARD_ID "freeBoardId", FBF.ORIGINAL_FILE_NAME as "originalFileName"
    , FBF.STORED_FILE_NAME as "storedFileName"
    , ROUND(FBF.FREE_BOARD_FILE_SIZE/1024, 1) as "freeBoardFileSize" 
FROM FREE_BOARD_FILE FBF
WHERE FBF.FREE_BOARD_ID = 132;