CREATE TABLE FREE_BOARD(
  FREE_BOARD_ID NUMBER NOT NULL,
  MEMBER_NO NUMBER NOT NULL,
  FREE_BOARD_TITLE VARCHAR2(765) NOT NULL,
  FREE_BOARD_CONTENT VARCHAR2(4000) NOT NULL,
  FREE_BOARD_WRITER VARCHAR2(200) NOT NULL,
  CREATE_DATE DATE NOT NULL,
  UPDATE_DATE DATE NOT NULL
);

COMMENT ON TABLE FREE_BOARD IS '자유게시판';

COMMENT ON COLUMN FREE_BOARD.FREE_BOARD_ID IS '자유게시판 번호';
COMMENT ON COLUMN FREE_BOARD.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN FREE_BOARD.FREE_BOARD_TITLE IS '자유게시판 주제';
COMMENT ON COLUMN FREE_BOARD.FREE_BOARD_CONTENT IS '자유게시판 본문';
COMMENT ON COLUMN FREE_BOARD.FREE_BOARD_WRITER IS '자유게시판 작성자(회원명)';
COMMENT ON COLUMN FREE_BOARD.CREATE_DATE IS '자유게시판 생성날짜';
COMMENT ON COLUMN FREE_BOARD.UPDATE_DATE IS '자유게시판 수정날짜';

ALTER TABLE FREE_BOARD 
ADD CONSTRAINT FREE_BOARD_ID_PK 
PRIMARY KEY(FREE_BOARD_ID);

ALTER TABLE FREE_BOARD 
ADD CONSTRAINT FREE_BOARD_MEMBER_NO_FK
FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO);

CREATE SEQUENCE FREE_BOARD_ID_SEQ
INCREMENT BY 1
START WITH 1;