SELECT *
FROM FREE_BOARD;

DESC FREE_BOARD;

SELECT  FREE_BOARD_ID, MEMBER_NO, FREE_BOARD_TITLE, FREE_BOARD_CONTENT, 
        FREE_BOARD_WRITER, CREATE_DATE, UPDATE_DATE
FROM FREE_BOARD
ORDER BY FREE_BOARD_ID DESC;

INSERT INTO free_board
VALUE(  FREE_BOARD_ID, MEMBER_NO, FREE_BOARD_TITLE, FREE_BOARD_CONTENT, 
        FREE_BOARD_WRITER, CREATE_DATE, UPDATE_DATE)
VALUES(FREE_BOARD_ID_SEQ.NEXTVAL, 1, '자유게시판이라', '자유란 무엇인가, 이 질문에 답할 수 있는 사람은 얼마나 될까',
'홍길동', SYSDATE, SYSDATE);

INSERT INTO free_board
VALUE(  FREE_BOARD_ID, MEMBER_NO, FREE_BOARD_TITLE, FREE_BOARD_CONTENT, 
        FREE_BOARD_WRITER, CREATE_DATE, UPDATE_DATE)
VALUES(FREE_BOARD_ID_SEQ.NEXTVAL, 2, '자유?', '이 세상에 자유란 없다 억압하는 세상이지',
'임꺽정', SYSDATE, SYSDATE);

INSERT INTO free_board
VALUE(  FREE_BOARD_ID, MEMBER_NO, FREE_BOARD_TITLE, FREE_BOARD_CONTENT, 
        FREE_BOARD_WRITER, CREATE_DATE, UPDATE_DATE)
VALUES(FREE_BOARD_ID_SEQ.NEXTVAL, 4, '자유는 있다', '자유란 아무걱정도 없는 것이다 BY BG',
'이몽룡', SYSDATE, SYSDATE);

COMMIT;


----------------자유게시판 상세페이지----------------
SELECT FB.MEMBER_NO, FB.FREE_BOARD_TITLE, 
        FB.FREE_BOARD_WRITER, FB.FREE_BOARD_ID,
        M.EMAIL, FB.CREATE_DATE,
        FB.FREE_BOARD_CONTENT 
FROM FREE_BOARD FB INNER JOIN member M
ON FB.MEMBER_NO = M.MEMBER_NO
WHERE fb.free_board_id = 1;

